name: Validate
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint lesson2 with golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          go-version: 1.16.x
          version: v1.35.1
          working-directory: lesson2